### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by denbatte** [RogerSelwyn/MS365-Mail#2]
Hi Roger,

Thanks for the work. Let me start by explaining that I am not a programmer/developer. I know what an API is and usually I manage to get things installed (I am the dangerous type of user). The thing is; I would love to have my O365 integrated (mail, calendar, ...). However, when I try to authenticate, the page stays blank.

I would appreciate it if there was a little more (updated/structured) documentation, and I can definitely help with that.
You are welcome to reach out.

**Comment by RogerSelwyn** [comment]
I'm not sure what you mean by the page stays blank. If you click on the link to authenticate, and your browser is already authenticate to MS, then you just need to copy the url at the top back into the provided space in the pop up and click submit.

**Comment by denbatte** [comment]
Thanks for the swift response! I have it working now.
I will fork the repo and work a bit on the documentation later this week. Thanks for the work!

**Comment by RogerSelwyn** [comment]
> Thanks for the swift response! I have it working now. I will fork the repo and work a bit on the documentation later this week. Thanks for the work!

Thank you, any input is welcomed
