### ISSUE TITLE
Single Mailbox is OK, but when adding a shared Mailbox  I get an error

### ISSUE THREAD

**Issue by Stephan-4711** [RogerSelwyn/MS365-Mail#5]
I added my ExOnline Mailbox, which is working. 

But when I reconfigure the intergation (after I added the API Permissions for the SharedMailbox) to add my sharedmailbox there is this error:

Logger: O365.connection
Source: /usr/local/lib/python3.12/site-packages/O365/connection.py:838
First occurred: 2:43:45 PM (26 occurrences)
Last logged: 2:56:58 PM

Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/users/ShareMailbox@MyDOmain.de/mailboxSettings | Error Message: Access is denied. Check credentials and try again. | Error Code:

**Comment by RogerSelwyn** [comment]
Did you re-autneticate?

**Comment by RogerSelwyn** [comment]
Disable auto-reply management, it's trying to get mailboxsettings for the shared mailbox, which it looks like it does not have permission for. I'm not sure under what conditions you would have permissions of it. It seems there is no 'shared' version of the permission, so maybe ms graph doesn't support mailbox settings for shared mailboxes.
